name: ServerForms
main: me.supernova1992.serverforms.ServerForms
version: 1.1.0
commands:
    apply:
        description: Apply to the server!
        permission: ServerForms.apply
        usage: /<command> formName
    readapp:
        description: Get the latest applications
        permission: ServerForms.readapp
        usage: /<command>
permissions:
    ServerForms.*:
        description: All command permissions
        children: 
            ServerForms.apply: true
            ServerForms.readapp: true
    ServerForms.apply:
        description: Apply command
        default: true
    ServerForms.readapp:
        description: Read Application
        default: false