name: ServerForms
main: me.supernova1992.applicationplugin.ServerForms
version: 1.0.0
commands:
    apply:
        description: Apply to the server!
        permission: ServerForms.apply
        usage: /<command> formName
    readapp:
        description: Get the latest applications
        permission: ServerForms.readapp
        usage: /<command> formName
    formlist:
        description: List available forms!
        permission: ServerForms.formlist
        usage: /<command>
permissions:
    ServerForms.*:
        description: All command permissions
        children: 
            ServerForms.apply: true
            ServerForms.readapp: true
            ServerForms.formlist: true
    ServerForms.apply:
        description: Apply command
        default: true
    ServerForms.readapp:
        description: Read last submitted Application
        default: false
    ServerForms.formlist:
        description: List available forms
        default: true